### ISSUE TITLE
Neodash is not loading the dashboard

### ISSUE THREAD

**Issue by rajakushwah** [nielsdejong/neodash#53] opened 2022-01-04 10:59 UTC
Hi Team,

I have performed the mandatory update of Neodash on Monday (3/01/22). After updating to the latest version (2.0.4) the Neodash is crashing and showing a white screen after a few seconds.

Issue - Dashboards are automatically getting closed as soon as we load them under Neodash. This is happening after updating Neodash to the latest version(2.0.4)

Please find the details below and the attached screenshot for more information - 

Neo4j Desktop Version - 1.4.11
Neo4j DB Version - 4.2.10
Neodash Version - 2.0.4

![image](https://user-images.githubusercontent.com/39225004/148049104-98e37b66-4c5d-4469-8cb1-cc24b369bf84.png)

Also please suggest a way to downgrade the Neodash version

**Comment by nielsdejong** [comment] 2022-01-04 20:09
Hi,

Thank you for the message.
I'll take a look if I can figure out what is causing the problems on your side.

Couple of questions:
- does the app crash for any kind of dashboard you load? Does creating a new dashboard work okay?
- what was the previous version that did work for you? 2.0.3?
- Does reinstalling the graph app fix the issue?
- if your dashboard was saved to the database, could you share your dashboard file with me? (The properties on the `_Neodash_Dashboard` node in the database).

Currently there is no way of downgrading the version in Neo4j Desktop. You could try to build the 2.0.3 release and host it yourself: https://github.com/nielsdejong/neodash/releases

Maybe worth a try. Let.me know if there's anything else you can share that might help me solve the issue.

Thank you,
Niels

**Comment by rajakushwah** [comment] 2022-01-06 08:47
Hi @nielsdejong ,

Thanks for a quick response..!!

Please find the answers to your question and also I'm attaching a dashboard that is working fine and the one which is crashing.

1. Does the app crash for any kind of dashboard you load? Does creating a new dashboard work okay?
    Yes, the app crashes when I load the attached dashboard with the name **dashboard-error.json** and works fine with the 
    dashboard -  **dashboard.json**. The only difference I could see between both is setting parameter - 
     **"clearParameterOnFieldClear": false**. 
    Also, it crashes sometimes when I use multiple pages in one dashboard. The issue still persists in creating a new dashboard 
    too.

2. what was the previous version that did work for you? 2.0.3? 
    Yes, Previously I was using version 2.0.3. Also, I tried to load the dashboard by downgrading the neodash to 2.0.3 but with 
    that also I am facing a similar issue.

3. Does reinstalling the graph app fix the issue?
     No, It doesn't fix anything


Dashboard



[Desktop.zip](https://github.com/nielsdejong/neodash/files/7820535/Desktop.zip)

**Comment by nielsdejong** [comment] 2022-01-07 13:06
Hi @rajakushwah ,

Thanks for sharing the dashboard files. I've resolved the problem in this commit: https://github.com/nielsdejong/neodash/commit/9485dd9c3ef905cc5c6bc7cd3d76e3857aea10a9

Will publish the 2.0.5 this weekend, so you can validate that things are working from you side. 
Once that is out, could you let me know if everything works?

**Comment by nielsdejong** [comment] 2022-01-09 19:14
Just published 2.0.5, could you check if the issue is resolved @rajakushwah ?

**Comment by rajakushwah** [comment] 2022-01-10 04:38
Hi @nielsdejong ,

That works fine with the latest release 2.0.5.

Thanks for quickly resolving it. I really appreciate your prompt and attentive response. 

Also, I'm curious to know if we can change the size of the single value dashboard to (3*1). The minimum size I could see is 3*3.

![image](https://user-images.githubusercontent.com/39225004/148718722-a810f7e7-49c8-4dcb-a4dc-2ba43c237001.png)

**Comment by nielsdejong** [comment] 2022-01-11 12:19
Great!
As for your other question, this is currently not possible from the UI. You can however, modify the save file directly to get a (3x1) size:
```
   {
      "title": "",
      "reports": [
        {
          "title": "",
          "query": "// $neodash_person_name\nMATCH (n:`Person`) \nWHERE toLower(toString(n.`name`)) CONTAINS toLower($input) \nRETURN DISTINCT n.`name` as value LIMIT 5",
          "width": 3,
          "type": "select",
          "height": 1,
          "selection": {},
          "settings": {}
        }
      ]
    },
    ```
    
   Perhaps you could try this out. Be warned that messing around with the save file can sometimes lead to unexpected behaviour, especially when using fractional sizes.
   
   Going to close this issue - if there's any other questions coming up please reach out!

**Closed by nielsdejong** 2022-01-11 12:19 UTC
