### ISSUE TITLE
Dashboard sharing functionality erroring out

### ISSUE THREAD

**Issue by emigre459** [nielsdejong/neodash#60] opened 2022-01-11 17:57 UTC
When I try to share the dashboard via Share from Neo4j, another user I send the link to can't load it (error message attached). It appears to be having issues with the credentials, but I've set `Include Connection Details` and `Standalone Dashboard` both to "Yes". Note that I've tested this on both an HTTP-accessible Neo4j server and an HTTPS-accessible one, with the same problem both times. Any ideas on what could be happening? Note that I get the same error as the other user if I try to open the link.

![image](https://user-images.githubusercontent.com/11720378/148995949-0198a480-130d-4a39-9938-4df8dc1ae2cf.png)

**Comment by nielsdejong** [comment] 2022-01-13 09:00
hi @emigre459, thanks for this.
I've seen this issue before myself, but I wasn't able to reproduce it.
My gut feel is that something goes wrong with the URL encoding/decoding of the connection details.

Could you share your Share URL with me so I can check? (possibly in a private message with the password/username removed)

**Comment by dbl94** [comment] 2022-01-13 09:52
Hi, I just wanted to leave a comment that I have encountered the same issue, but unfortunately did not manage to figure it out yet, I will update here if I manage to make it work.
 
In my example, I have created a Neodash dashboard based on my Neo4j Aura database, and when I share it as a standalone non-editable version for others to see the dashboard, it shows the same error upon opening the link.

I'm not sure, maybe it has something to do with the Aura's Neo4j+s:// connection perhaps?

**Comment by nukerxy** [comment] 2022-01-14 15:38
> One other thing I figured I'd flag though: once I corrected the capitalization issue in the URL for my password, it did indeed load the dashboard, but a new error pops up soon after connecting to the dashboard, shown in the screenshot attached here. I _think_ this may have to do with the dashboard tab it's auto-loading to having an unfinished Parameter Select tile, but not sure.

This happened to me aswell, but I am unable to reproduce it consistently. 

- I was using the "demo" on  http://neodash.graphapp.io.
- using "exisiting" dashboard (saved in Browser)
- established connection

I reckon (not too sure), the error occurred when I accessed neodash again, after previously closing it (same browser session)

Low impact anyway, just close the window and everything is fine.
Might consider opening another issue..

**Comment by nielsdejong** [comment] 2022-01-18 13:26
Thanks @emigre459 @dbl94 @nukerxy ,
I've fixed the incorrect lowercasing of the share URL here: https://github.com/nielsdejong/neodash/commit/41e59b1508b3fd140391855d71f27ddadbb1faeb

The error that you both spotted around accessing `fields` on an undefined object is something that I've seen pop-up in several places. Seems to be a race condition somewhere that I'll need to dig into further. (You can actually produce a similar error by switching pages really fast). 

Going to close this issue and look into the other problem further. I'll publish the 2.0.6 release sometime this weekend so you can  check if everything works from your side. 

Best,
Niels

**Closed by nielsdejong** 2022-01-18 13:26 UTC
